# Database
SQL_ENGINE = 'django.db.backends.postgresql'
SQL_DATABASE = 'postgres'
SQL_USER = 'postgres'
SQL_PASSWORD = 'pass'
SQL_HOST = '127.0.0.1'
SQL_PORT = 5432

# REDIS
REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379

# Chat-bot
CHAT_BOT_TOKEN = '1645389505:AAFmMxB16xTgLwfxnWmlACo8HahSqUhS6pA'

# AWS
AWS_ACCESS_KEY_ID = 'AKIAX3EUZUQFH6WATCSX'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'business-net-pictures'